models.py
from datetime import datetime
from settings import db


class Posts(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    created = db.Column(db.DateTime, default=datetime.now().replace(microsecond=0))
    title = db.Column(db.Text)
    content = db.Column(db.Text)

account/auth.py
from flask import Blueprint, redirect, url_for, render_template, request, flash
from .model import User

from flask_login import login_user, current_user, login_required, logout_user

from werkzeug.security import generate_password_hash, check_password_hash
from settings import db


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['POST', 'GET'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        user = User.query.filter_by(email=email).first()
        rem = True if request.form.get('remember') else False
        if not user or not check_password_hash(user.password, password):
            flash('Логин или пароль введены неверно!')
            return  render_template('login/login.html')
        login_user(user, remember=rem)

        return redirect(url_for('auth.profile'))
    else:
        return render_template('login/login.html')


@auth.route('/signup', methods=['POST', 'GET'])
def signup():
    if request.method == 'POST':
        email = request.form.get('email')
        name = request.form.get('name')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Такая почта уже есть!')

        new_user = User(name, generate_password_hash(password, method='sha256'), email)
        db.session.add(new_user)
        db.session.commit()
        db.session.close()
        return redirect(url_for('auth.login'))
    else:
        return render_template('login/signup.html')


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('posts.main'))


@auth.route('/profile')
@login_required
def profile():
    return render_template('login/profile.html', username=current_user.name )

views/posts.py
import sqlite3
from flask import Flask, render_template, abort, request, flash
from flask import redirect, url_for
from flask import Blueprint


posts_bp = Blueprint('posts', __name__)


def get_db_connection():
    conn = sqlite3.connect('database.db')
    conn.row_factory = sqlite3.Row
    return conn


@posts_bp.route('/')
def main():
    conn = get_db_connection()
    posts = conn.execute('SELECT * FROM posts').fetchall()
    conn.close()
    return render_template('main.html', posts=posts)


@posts_bp.route('/post/<int:post_id>')
def show_post(post_id):
    conn = get_db_connection()
    post = conn.execute('SELECT * FROM posts WHERE id=?', (post_id,)).fetchone()
    conn.close()
    if post is None:
        abort(404)
    return render_template('post.html', post=post)


@posts_bp.route('/post/create', methods=('GET', 'POST'))
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']

        if not title:
            flash('Укажите заголовок!!!')
        if not content:
            flash("Укажите содержание!!!")
        else:
            conn = get_db_connection()
            conn.execute('INSERT INTO posts (title, content) values (?, ?)', (title, content))
            conn.commit()
            conn.close()
            return redirect(url_for('main'))
    return render_template('create.html')


@posts_bp.route('/post/edit/<int:post_id>', methods=('GET', 'POST'))
def edit_post(post_id):
    conn = get_db_connection()
    post = conn.execute('SELECT * FROM posts WHERE id=?', (post_id,)).fetchone()
    conn.close()
    if post is None:
        abort(404)

    if request.method=='POST':
        title = request.form['title']
        content = request.form['content']

        if not title:
            flash('Укажите заголовок!!!')
        if not content:
            flash("Укажите содержание!!!")
        if content and title:
            conn = get_db_connection()
            conn.execute('UPDATE posts SET title=?, content=? WHERE id =?', (title, content, post_id))
            conn.commit()
            conn.close()
            return redirect(url_for('posts.show_post', post_id=post_id))

    return render_template('edit.html', post=post)


@posts_bp.route('/post/delete/<int:post_id>', methods=('POST',))
def delete_post(post_id):
    conn = get_db_connection()
    post = conn.execute('SELECT * FROM posts WHERE id=?', (post_id,)).fetchone()
    conn.close()
    if post is None:
        abort(404)

    conn = get_db_connection()
    conn.execute(f'DELETE FROM posts WHERE id={post_id}')
    conn.commit()
    conn.close()
    flash(f'"{post["title"]}" был удалён')
    return redirect(url_for('posts.main'))

views/posts_with_orm.py
from flask import Flask, render_template, abort, request, flash
from flask import redirect, url_for
from flask import Blueprint
from models import Posts
from settings import db

from flask_login import login_required

postsbp = Blueprint('posts', __name__)


# def get_db_connection():
#     conn = sqlite3.connect('database.db')
#     conn.row_factory = sqlite3.Row
#     return conn


@postsbp.route('/')
def main():
    posts_ = Posts.query.all()
    return render_template('main.html', posts=posts_)


@postsbp.route('/post/<int:post_id>')
def show_post(post_id):
    posts_ = Posts.query.filter_by(id=post_id).first()
    if posts_ is None:
        abort(404)
    return render_template('post.html', post=posts_)


@postsbp.route('/post/create', methods=('GET', 'POST'))
@login_required
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']

        if not title:
            flash('Укажите заголовок!!!')
        if not content:
            flash("Укажите содержание!!!")
        else:
            posts_ = Posts(title=title, content=content)
            db.session.add(posts_)
            db.session.commit()
            return redirect(url_for('posts.main'))
    return render_template('create.html')


@postsbp.route('/post/edit/<int:post_id>', methods=('GET', 'POST'))
@login_required
def edit_post(post_id):
    posts_ = Posts.query.filter_by(id=post_id).first()

    if request.method == 'POST':
        posts_.title = request.form['title']
        posts_.content = request.form['content']

        if not posts_.title:
            flash('Укажите заголовок!!!')
        if not posts_.content:
            flash("Укажите содержание!!!")

        db.session.add(posts_)
        db.session.commit()
        return redirect(url_for('posts.show_post', post_id=post_id))
    return render_template('edit.html', post=posts_)


@postsbp.route('/post/delete/<int:post_id>', methods=('POST',))
@login_required
def delete_post(post_id):
    posts_= Posts.query.filter_by(id=post_id).first()
    db.session.delete(posts_)
    db.session.commit()
    flash(f'"{posts_["title"]}" был удалён')
    return redirect(url_for('posts.main'))

templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('posts.main')}}">FlaskBlog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('posts.create_post') }}">Create</a>
            </li>
            {% if not current_user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
            </li>
            {% endif %}
            {% if current_user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">LogOut</a>
            </li>
            {% endif%}
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block content %} {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/create.html
{% extends 'base.html' %}

{% block content %}
      {% for message in get_flashed_messages() %}
        <div class="alert alert-danger">{{ message }}</div>
      {% endfor %}
<h1>{% block title %} Create a New Post {% endblock %}</h1>

<form method="post">
    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" name="title"
               placeholder="Post title" class="form-control"
               value="{{ request.form['title'] }}"></input>
    </div>

    <div class="form-group">
        <label for="content">Content</label>
        <textarea name="content" placeholder="Post content"
                  class="form-control">{{ request.form['content'] }}</textarea>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Отправить</button>
    </div>
</form>
{% endblock %}

templates/edit.html
{% extends 'base.html' %}

{% block content %}
    {% for message in get_flashed_messages() %}
        <div class="alert alert-danger">{{ message }}</div>
    {% endfor %}
<h1>{% block title %} Edit "{{ post['title'] }}" {% endblock %}</h1>

<form method="post">
    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" name="title" placeholder="Post title"
               class="form-control"
               value="{{ request.form['title'] or post['title'] }}">
        </input>
    </div>

    <div class="form-group">
        <label for="content">Content</label>
        <textarea name="content" placeholder="Post content"
                  class="form-control">{{ request.form['content'] or post['content'] }}</textarea>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>
<hr>
<form action="{{ url_for('posts.delete_post', post_id=post['id']) }}" method="POST">
    <input type="submit" value="Delete Post"
            class="btn btn-danger btn-sm"
            onclick="return confirm('Вы уверены, что хотите удалить пост?')">
</form>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Flask Project</title>
    <link rel="stylesheet" href="{{url_for('static', filename= 'css/style.css') }}">
</head>
<body>
<h1> welcam! </h1>
<h2>Привет, разбраб </h2>
<p>{{ hi }}</p>
{% for h in hi:%}
<p>{{h}}</p>
{% endfor %}
</body>
</html>

templates/login/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>

<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('posts.main') }}" class="navbar-item">
                                Home
                            </a>
                            <a href="{{ url_for('auth.profile') }}" class="navbar-item">
                                Profile
                            </a>
                            {% else %}
                            <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                Login
                            </a>
                            <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                                Logout
                            </a>
                             {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

templates/login/login.html
{% extends "login/base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{messages[0] }}
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

templates/login/profile.html
{% extends "login/base.html" %}

{% block content %}
<h1 class="title">
  ПРивет, {{username}}
</h1>
{% endblock %}

templates/login/signup.html
{% extends "login/base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
         {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{messages[0] }}. <br> Перейдите на <a href="{{ url_for(auth.login) }}">Login</a>
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/signup">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}</html>

templates/main.html
{% extends 'base.html' %}

{% block title %}
    Главная страница
{% endblock %}

{% block content %}
    {% for message in get_flashed_messages() %}
        <div class="alert alert-danger">{{ message }}</div>
    {% endfor %}
    {% for post in posts %}
    <a href="{{url_for('posts.show_post', post_id=post['id'])}}">
        <h2>{{ post['title'] }}</h2>
    </a>
    <span class="badge badge-primary">{{ post['created']}}</span>
    <hr>
{% endfor %}
{% endblock %}

templates/post.html
{% extends 'base.html'%}

{% block content %}
    <h2>{% block title %} {{ post['title'] }} {%endblock %}</h2>
    <span class="badge badge-primary">{{ post['created']}}</span>

    <a href="{{url_for('posts.edit_post', post_id=post['id']) }}">
        <span class="badge badge-primary" style="color: white"> edit</span>
    </a>
    <p>{{post['content'].replace('\r\n', '<br>') | safe }}</p>
{% endblock %}